# Generated by Django 2.2.4 on 2019-08-08 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Description', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='', help_text='Term', max_length=100)),
                ('definition', models.CharField(default='', help_text='Definition', max_length=100)),
                ('image_url', models.CharField(blank=True, help_text='Image URL', max_length=500, null=True)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='words', to='dbapi.Database')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Description', max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='databases', to='dbapi.Folder'),
        ),
        migrations.AddField(
            model_name='database',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='databases', to=settings.AUTH_USER_MODEL),
        ),
    ]
