# Generated by Django 2.2.4 on 2019-08-08 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='words',
        ),
        migrations.AddField(
            model_name='database',
            name='description',
            field=models.CharField(help_text='Description', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.CharField(default='SET_NAME', help_text='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='database',
            field=models.ForeignKey(default='', on_delete='CASCADE', to='dbapi.Database'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(default='...', help_text='Definition', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_url',
            field=models.CharField(help_text='Image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='term',
            field=models.CharField(default='TERM', help_text='Term', max_length=100),
        ),
    ]
