# Generated by Django 2.2.4 on 2019-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0002_auto_20190807_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='database',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='dbapi.Database'),
        ),
    ]
