# Generated by Django 2.2.4 on 2019-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0002_leveldesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveldesc',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
