# Generated by Django 2.2.4 on 2019-08-09 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0003_leveldesc_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveldesc',
            name='lastAccess',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
