# Generated by Django 2.2.4 on 2019-08-09 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_leveldesc_lastaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='databases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leveldesc',
            name='db',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_levels', to='dbapi.Database'),
        ),
        migrations.AlterField(
            model_name='leveldesc',
            name='user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='database',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='words', to='dbapi.Database'),
        ),
    ]
