# Generated by Django 2.2.4 on 2019-08-08 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_auto_20190807_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='dbapi.Database'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(default='', help_text='Definition', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL', max_length=500, null=True),
        ),
    ]
