# Generated by Django 2.2.4 on 2019-08-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0006_auto_20190809_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.CharField(default='', help_text='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(default='', help_text='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(default='', help_text='Definition', max_length=1000),
        ),
    ]
