# Generated by Django 2.2.4 on 2019-08-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0007_auto_20190809_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.TextField(default='', help_text='Description'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.TextField(default='', help_text='Name'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(default='', help_text='Description'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.TextField(default='', help_text='Name'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(default='', help_text='Definition'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='term',
            field=models.TextField(default='', help_text='Term'),
        ),
    ]
