# Generated by Django 2.2.4 on 2019-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0008_auto_20190809_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(default='', help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='', help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL', max_length=500, null=True),
        ),
    ]
