# Generated by Django 2.2.4 on 2019-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0009_auto_20190809_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveldesc',
            name='mastered',
            field=models.IntegerField(default=0),
        ),
    ]
