# Generated by Django 2.2.4 on 2019-08-13 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbapi', '0010_leveldesc_mastered'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastShuffle', models.DateTimeField(blank=True, null=True)),
                ('shuffleCount', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_word_progress', to='dbapi.Word')),
            ],
        ),
    ]
