# Generated by Django 2.2.4 on 2019-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0011_wordprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveldesc',
            name='nextShuffle',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
