# Generated by Django 2.2.4 on 2019-08-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0012_leveldesc_nextshuffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordprogress',
            name='db',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_word_progress', to='dbapi.Database'),
        ),
    ]
